apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ose:selfservice
rules:
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  attributeRestrictions: null
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - update
- apiGroups: null
  attributeRestrictions: null
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - update
- apiGroups: null
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - update
- apiGroups: null
  attributeRestrictions: null
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups: null
  attributeRestrictions: null
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - create
  - list
  - get
- apiGroups: null
  attributeRestrictions: null
  resources:
  - services
  - endpoints
  verbs:
  - create
- apiGroups: null
  attributeRestrictions: null
  resources:
  - groups
  verbs:
  - get
- apiGroups: null
  attributeRestrictions: null
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - secrets
  verbs:
  - get
