apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: ose:selfservice
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  - resourcequotas
  verbs:
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - persistentvolumes
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  - user.openshift.io
  attributeRestrictions: null
  resources:
  - groups
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
